use_frameworks!

platform :ios, '10.0'

target 'TurboUPIUAT_Example' do
  pod 'TurboUPIUAT', :path => '../'

  target 'TurboUPIUAT_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
